# baseURL
@baseURL = http://localhost:3000/members

###
# Find All Members
GET {{ baseURL }}

###
# Find Member By Id
GET {{ baseURL }}/12

###
# Find Member By Discord Username
GET {{ baseURL }}
Content-Type: application/json

{
    "discordUsername":"davudi"
}

###
# Create Member
POST {{ baseURL }}
Content-Type: application/json

{
    "discordUsername":"exampleeesjkdhf"
}

###
# Delete Member By Id
DELETE {{ baseURL }}/18

###
# Delete Member By Discord Username
DELETE {{ baseURL }}
Content-Type: application/json

{
    "discordUsername":"newuser5"
}

###
# Warn Member about payment
POST {{ baseURL }}/warn/2
Content-Type: application/json

###
# Remove Member role from discord user
POST {{ baseURL }}/remove/2
Content-Type: application/json

###
# Get members to warn about payment
GET {{ baseURL }}/warn/get

###
# Get members to downgrade member role
GET {{ baseURL }}/downgrade/get

###
# Get members to upgrade to member role
GET {{ baseURL }}/upgrade/get
